// <auto-generated />
using System;
using Core.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Core.Migrations
{
    [DbContext(typeof(AgloDBContext))]
    partial class AgloDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Models.AglomMode.AglomRequestDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AglomResponseID")
                        .HasColumnType("integer");

                    b.Property<int>("CocksickID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FluxAdditionsID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<int>("StartEnterID")
                        .HasColumnType("integer");

                    b.Property<int>("ZolaOfCocksickID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AglomResponseID");

                    b.HasIndex("CocksickID");

                    b.HasIndex("FluxAdditionsID");

                    b.HasIndex("StartEnterID");

                    b.HasIndex("ZolaOfCocksickID");

                    b.ToTable("AglomRequests");
                });

            modelBuilder.Entity("Core.Models.AglomMode.AglomResponseDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AglomResponses");
                });

            modelBuilder.Entity("Core.Models.AglomMode.CocksickDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<double>("PercentC")
                        .HasColumnType("double precision");

                    b.Property<double>("PercentSera")
                        .HasColumnType("double precision");

                    b.Property<double>("PercentValotiles")
                        .HasColumnType("double precision");

                    b.Property<double>("PercentZola")
                        .HasColumnType("double precision");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Cocksicks");
                });

            modelBuilder.Entity("Core.Models.AglomMode.ComponentInfoDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AglomResponseID")
                        .HasColumnType("integer");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<double>("ReportAl2O3")
                        .HasColumnType("double precision");

                    b.Property<double>("ReportCaO")
                        .HasColumnType("double precision");

                    b.Property<double>("ReportCaO_SiO2")
                        .HasColumnType("double precision");

                    b.Property<double>("ReportComponentOfShihta")
                        .HasColumnType("double precision");

                    b.Property<double>("ReportFe")
                        .HasColumnType("double precision");

                    b.Property<double>("ReportFe2O3")
                        .HasColumnType("double precision");

                    b.Property<double>("ReportFeO")
                        .HasColumnType("double precision");

                    b.Property<double>("ReportMgO")
                        .HasColumnType("double precision");

                    b.Property<double>("ReportMnO")
                        .HasColumnType("double precision");

                    b.Property<double>("ReportOxideSum")
                        .HasColumnType("double precision");

                    b.Property<double>("ReportP")
                        .HasColumnType("double precision");

                    b.Property<double>("ReportPMPP")
                        .HasColumnType("double precision");

                    b.Property<double>("ReportS")
                        .HasColumnType("double precision");

                    b.Property<double>("ReportSiO2")
                        .HasColumnType("double precision");

                    b.Property<double>("ReportTiO2")
                        .HasColumnType("double precision");

                    b.Property<double>("ReportZn")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AglomResponseID");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("Core.Models.AglomMode.FluxAdditionsDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DolomyteAl2O3")
                        .HasColumnType("double precision");

                    b.Property<double>("DolomyteCaO")
                        .HasColumnType("double precision");

                    b.Property<double>("DolomyteMgO")
                        .HasColumnType("double precision");

                    b.Property<double>("DolomytePMPP")
                        .HasColumnType("double precision");

                    b.Property<double>("DolomyteSiO2")
                        .HasColumnType("double precision");

                    b.Property<double>("IzvestnyakAl2O3")
                        .HasColumnType("double precision");

                    b.Property<double>("IzvestnyakCaO")
                        .HasColumnType("double precision");

                    b.Property<double>("IzvestnyakMgO")
                        .HasColumnType("double precision");

                    b.Property<double>("IzvestnyakPMPP")
                        .HasColumnType("double precision");

                    b.Property<double>("IzvestnyakSiO2")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("FluxAdditionss");
                });

            modelBuilder.Entity("Core.Models.AglomMode.ShihtaComponentDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AglomRequestID")
                        .HasColumnType("integer");

                    b.Property<double>("Al2O3")
                        .HasColumnType("double precision");

                    b.Property<double>("CaO")
                        .HasColumnType("double precision");

                    b.Property<double>("Cr")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Fe")
                        .HasColumnType("double precision");

                    b.Property<double>("FeO")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<double>("MgO")
                        .HasColumnType("double precision");

                    b.Property<double>("MnO")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("P")
                        .HasColumnType("double precision");

                    b.Property<double>("PMPP")
                        .HasColumnType("double precision");

                    b.Property<double>("S")
                        .HasColumnType("double precision");

                    b.Property<double>("SiO2")
                        .HasColumnType("double precision");

                    b.Property<double>("TiO2")
                        .HasColumnType("double precision");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.Property<double>("Wet")
                        .HasColumnType("double precision");

                    b.Property<double>("Zn")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AglomRequestID");

                    b.ToTable("ShihtaComponents");
                });

            modelBuilder.Entity("Core.Models.AglomMode.StartEnterDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DolomyteInAgl")
                        .HasColumnType("double precision");

                    b.Property<double>("FeOinAgl")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<double>("osnovnost")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("StartEnters");
                });

            modelBuilder.Entity("Core.Models.AglomMode.ZolaOfCocksickDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Al2O3")
                        .HasColumnType("double precision");

                    b.Property<double>("CaO")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Fe")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<double>("MgO")
                        .HasColumnType("double precision");

                    b.Property<double>("P")
                        .HasColumnType("double precision");

                    b.Property<double>("SiO2")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("ZolaOfCocksicks");
                });

            modelBuilder.Entity("Core.Models.AglomMode.AglomRequestDB", b =>
                {
                    b.HasOne("Core.Models.AglomMode.AglomResponseDB", "AglomResponse")
                        .WithMany()
                        .HasForeignKey("AglomResponseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.AglomMode.CocksickDB", "Cocksick")
                        .WithMany()
                        .HasForeignKey("CocksickID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.AglomMode.FluxAdditionsDB", "FluxAdditions")
                        .WithMany()
                        .HasForeignKey("FluxAdditionsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.AglomMode.StartEnterDB", "StartEnter")
                        .WithMany()
                        .HasForeignKey("StartEnterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.AglomMode.ZolaOfCocksickDB", "ZolaOfCocksick")
                        .WithMany()
                        .HasForeignKey("ZolaOfCocksickID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AglomResponse");

                    b.Navigation("Cocksick");

                    b.Navigation("FluxAdditions");

                    b.Navigation("StartEnter");

                    b.Navigation("ZolaOfCocksick");
                });

            modelBuilder.Entity("Core.Models.AglomMode.ComponentInfoDB", b =>
                {
                    b.HasOne("Core.Models.AglomMode.AglomResponseDB", "AglomResponse")
                        .WithMany("Components")
                        .HasForeignKey("AglomResponseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AglomResponse");
                });

            modelBuilder.Entity("Core.Models.AglomMode.ShihtaComponentDB", b =>
                {
                    b.HasOne("Core.Models.AglomMode.AglomRequestDB", "AglomRequest")
                        .WithMany("ShihtaComponents")
                        .HasForeignKey("AglomRequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AglomRequest");
                });

            modelBuilder.Entity("Core.Models.AglomMode.AglomRequestDB", b =>
                {
                    b.Navigation("ShihtaComponents");
                });

            modelBuilder.Entity("Core.Models.AglomMode.AglomResponseDB", b =>
                {
                    b.Navigation("Components");
                });
#pragma warning restore 612, 618
        }
    }
}
