// <auto-generated />
using System;
using Core.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Core.Migrations.SlagModeDB
{
    [DbContext(typeof(SlagModeDBContext))]
    [Migration("20260113134740_AddedTables")]
    partial class AddedTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChargeComponentRequest", b =>
                {
                    b.Property<int>("ComponentsId")
                        .HasColumnType("integer");

                    b.Property<int>("RequestsId")
                        .HasColumnType("integer");

                    b.HasKey("ComponentsId", "RequestsId");

                    b.HasIndex("RequestsId");

                    b.ToTable("ChargeComponentRequest");
                });

            modelBuilder.Entity("Core.Models.SlagMode.CastIron", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("C")
                        .HasColumnType("double precision");

                    b.Property<double>("Cr")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<double>("Mn")
                        .HasColumnType("double precision");

                    b.Property<double>("S")
                        .HasColumnType("double precision");

                    b.Property<double>("Si")
                        .HasColumnType("double precision");

                    b.Property<double>("Temp")
                        .HasColumnType("double precision");

                    b.Property<double>("Ti")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("CastIrons");
                });

            modelBuilder.Entity("Core.Models.SlagMode.ChargeComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Al2O3")
                        .HasColumnType("double precision");

                    b.Property<double>("CaO")
                        .HasColumnType("double precision");

                    b.Property<double>("Consumption")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Fe")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<double>("MgO")
                        .HasColumnType("double precision");

                    b.Property<double>("MnO")
                        .HasColumnType("double precision");

                    b.Property<double>("S")
                        .HasColumnType("double precision");

                    b.Property<double>("SiO2")
                        .HasColumnType("double precision");

                    b.Property<string>("Sourcename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TiO2")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("ChargeComponents");
                });

            modelBuilder.Entity("Core.Models.SlagMode.InputCoke", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AshAl2O3Fraction")
                        .HasColumnType("double precision");

                    b.Property<double>("AshAmount")
                        .HasColumnType("double precision");

                    b.Property<double>("AshCaOFraction")
                        .HasColumnType("double precision");

                    b.Property<double>("AshMgOFraction")
                        .HasColumnType("double precision");

                    b.Property<double>("AshSiO2Fraction")
                        .HasColumnType("double precision");

                    b.Property<double>("Consumption")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<double>("Sulfur")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("InputCoke");
                });

            modelBuilder.Entity("Core.Models.SlagMode.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CastIronID")
                        .HasColumnType("integer");

                    b.Property<int>("CokeID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<int>("SlagID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CastIronID");

                    b.HasIndex("CokeID");

                    b.HasIndex("SlagID");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("Core.Models.SlagMode.Response", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("BalSlagMass")
                        .HasColumnType("double precision");

                    b.Property<double>("CaOBalSlagMass")
                        .HasColumnType("double precision");

                    b.Property<double>("CastIronTemp")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<double>("CurrSlagViscosity")
                        .HasColumnType("double precision");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Gradient_1400_1500")
                        .HasColumnType("double precision");

                    b.Property<double>("Gradient_7_25")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<double>("MaterialCons")
                        .HasColumnType("double precision");

                    b.Property<double>("PropAglo23")
                        .HasColumnType("double precision");

                    b.Property<double>("PropAglo4")
                        .HasColumnType("double precision");

                    b.Property<double>("PropBfAddict")
                        .HasColumnType("double precision");

                    b.Property<double>("PropKach")
                        .HasColumnType("double precision");

                    b.Property<double>("PropLeb")
                        .HasColumnType("double precision");

                    b.Property<double>("PropMinInclude")
                        .HasColumnType("double precision");

                    b.Property<double>("PropMix")
                        .HasColumnType("double precision");

                    b.Property<double>("PropOre")
                        .HasColumnType("double precision");

                    b.Property<double>("PropSsgpo")
                        .HasColumnType("double precision");

                    b.Property<double>("PropWeldSlag")
                        .HasColumnType("double precision");

                    b.Property<int>("RequestID")
                        .HasColumnType("integer");

                    b.Property<double>("SActivity")
                        .HasColumnType("double precision");

                    b.Property<double>("SContentInCastIron")
                        .HasColumnType("double precision");

                    b.Property<double>("SDistribution")
                        .HasColumnType("double precision");

                    b.Property<double>("SlagBasicity1")
                        .HasColumnType("double precision");

                    b.Property<double>("SlagBasicity2")
                        .HasColumnType("double precision");

                    b.Property<double>("SlagBasicity3")
                        .HasColumnType("double precision");

                    b.Property<double>("SlagBasicityKulikov")
                        .HasColumnType("double precision");

                    b.Property<double>("SlagOut")
                        .HasColumnType("double precision");

                    b.Property<double>("SlagTemperature")
                        .HasColumnType("double precision");

                    b.Property<double>("SlagTemperature_25Puaz")
                        .HasColumnType("double precision");

                    b.Property<double>("Temp_7_Puaz")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalAglo")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalSInOre")
                        .HasColumnType("double precision");

                    b.Property<double>("Viscosity_1400")
                        .HasColumnType("double precision");

                    b.Property<double>("Viscosity_1450")
                        .HasColumnType("double precision");

                    b.Property<double>("Viscosity_1500")
                        .HasColumnType("double precision");

                    b.Property<double>("Viscosity_1550")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("RequestID")
                        .IsUnique();

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("Core.Models.SlagMode.Slag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Al2O3")
                        .HasColumnType("double precision");

                    b.Property<double>("CaO")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<double>("MgO")
                        .HasColumnType("double precision");

                    b.Property<double>("SiO2")
                        .HasColumnType("double precision");

                    b.Property<double>("TiO2")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Slags");
                });

            modelBuilder.Entity("ChargeComponentRequest", b =>
                {
                    b.HasOne("Core.Models.SlagMode.ChargeComponent", null)
                        .WithMany()
                        .HasForeignKey("ComponentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.SlagMode.Request", null)
                        .WithMany()
                        .HasForeignKey("RequestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Models.SlagMode.Request", b =>
                {
                    b.HasOne("Core.Models.SlagMode.CastIron", "CastIron")
                        .WithMany()
                        .HasForeignKey("CastIronID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.SlagMode.InputCoke", "InputCoke")
                        .WithMany()
                        .HasForeignKey("CokeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.SlagMode.Slag", "Slag")
                        .WithMany()
                        .HasForeignKey("SlagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CastIron");

                    b.Navigation("InputCoke");

                    b.Navigation("Slag");
                });

            modelBuilder.Entity("Core.Models.SlagMode.Response", b =>
                {
                    b.HasOne("Core.Models.SlagMode.Request", "Request")
                        .WithOne("Response")
                        .HasForeignKey("Core.Models.SlagMode.Response", "RequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Core.Models.SlagMode.Request", b =>
                {
                    b.Navigation("Response")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
