FROM mcr.microsoft.com/dotnet/runtime:8.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore CalculationHistoryWriter/CalculationHistoryWriter.csproj
RUN dotnet publish CalculationHistoryWriter/CalculationHistoryWriter.csproj -c Release -o /app/publish --no-restore

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "CalculationHistoryWriter.dll"]
