syntax = "proto3";

option csharp_namespace = "Contracts.Grpc";

package calculations;

service AglomCalculator {
  rpc Calculate (CalculationRequest) returns (CalculationReply);
  rpc CheckHealth (HealthRequest) returns (HealthReply);
}

service GasDynamicCalculator {
  rpc Calculate (CalculationRequest) returns (CalculationReply);
  rpc CheckHealth (HealthRequest) returns (HealthReply);
}

service SlagCalculator {
  rpc Calculate (CalculationRequest) returns (CalculationReply);
  rpc CheckHealth (HealthRequest) returns (HealthReply);
}

service FurnaceService {
  rpc Calculate (CalculationRequest) returns (CalculationReply);
  rpc CheckHealth (HealthRequest) returns (HealthReply);
}

message CalculationRequest {
  string json = 1;
  string request_id = 2;
  string module = 3;
  string correlation_id = 4;
}

message CalculationReply {
  string json = 1;
  string request_id = 2;
  string module = 3;
  string status = 4;
  string error_code = 5;
  string error_message = 6;
  string correlation_id = 7;
}

message HealthRequest {}
message HealthReply { string status = 1; string module = 2; }
