// <auto-generated />
using System;
using Core.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Core.Migrations.GasDynamicDB
{
    [DbContext(typeof(GasDynamicDBContext))]
    [Migration("20251207090643_GasDynamicInit")]
    partial class GasDynamicInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Models.GasDynamic.Aglom.Inputs.AglomContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AglomInputModelId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("FractionPercentage")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<double>("MinFractionSize")
                        .HasColumnType("double precision");

                    b.Property<double>("Porosity")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AglomInputModelId");

                    b.ToTable("AglomContents");
                });

            modelBuilder.Entity("Core.Models.GasDynamic.Aglom.Inputs.AglomInputModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AglomInputs");
                });

            modelBuilder.Entity("Core.Models.GasDynamic.Aglom.Inputs.KoksContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AglomInputModelId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("FractionPercentage")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<double>("MinFractionSize")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AglomInputModelId");

                    b.ToTable("KoksContents");
                });

            modelBuilder.Entity("Core.Models.GasDynamic.Aglom.Inputs.OkatContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AglomInputModelId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("FractionPercentage")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<double>("MinFractionSize")
                        .HasColumnType("double precision");

                    b.Property<double>("Porosity")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AglomInputModelId");

                    b.ToTable("OkatContents");
                });

            modelBuilder.Entity("Core.Models.GasDynamic.Aglom.Outputs.AglomOutputModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AglomPorosity")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<double>("OkatPorosity")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("AglomOutputs");
                });

            modelBuilder.Entity("Core.Models.GasDynamic.Base.Inputs.BlastFurnaceInputModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompositionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FuelAndBlastId")
                        .HasColumnType("integer");

                    b.Property<int>("GeometryId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<int>("MaterialsId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionId")
                        .HasColumnType("integer");

                    b.Property<int>("ThermalAndPressureId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompositionId");

                    b.HasIndex("FuelAndBlastId");

                    b.HasIndex("GeometryId");

                    b.HasIndex("MaterialsId");

                    b.HasIndex("ProductionId");

                    b.HasIndex("ThermalAndPressureId");

                    b.ToTable("BlastFurnaceInputs");
                });

            modelBuilder.Entity("Core.Models.GasDynamic.Base.Inputs.CompositionParameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("C_chugun")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Fe_chugun")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<double>("Mn_chugun")
                        .HasColumnType("double precision");

                    b.Property<double>("P_chugun")
                        .HasColumnType("double precision");

                    b.Property<double>("S_shlak")
                        .HasColumnType("double precision");

                    b.Property<double>("Si_chugun")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("CompositionParameters");
                });

            modelBuilder.Entity("Core.Models.GasDynamic.Base.Inputs.FuelAndBlastParameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("C_neletuch")
                        .HasColumnType("double precision");

                    b.Property<double>("C_prir_gaz")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("H2_prir_gaz")
                        .HasColumnType("double precision");

                    b.Property<double>("Kislorod_dut")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<double>("Poteri_dut")
                        .HasColumnType("double precision");

                    b.Property<double>("Rashod_dut")
                        .HasColumnType("double precision");

                    b.Property<double>("Stepen_CO")
                        .HasColumnType("double precision");

                    b.Property<double>("Stepen_pryamogo_vost")
                        .HasColumnType("double precision");

                    b.Property<double>("Stepen_vodorod")
                        .HasColumnType("double precision");

                    b.Property<double>("Udeln_koks")
                        .HasColumnType("double precision");

                    b.Property<double>("Udeln_prir_gaz")
                        .HasColumnType("double precision");

                    b.Property<double>("Vlazhn_dut")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("FuelAndBlastParameters");
                });

            modelBuilder.Entity("Core.Models.GasDynamic.Base.Inputs.FurnaceGeometry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Diam_furm")
                        .HasColumnType("double precision");

                    b.Property<double>("Diam_gorn")
                        .HasColumnType("double precision");

                    b.Property<double>("Diam_koloshnik")
                        .HasColumnType("double precision");

                    b.Property<double>("Diam_raspar")
                        .HasColumnType("double precision");

                    b.Property<double>("Dlina_furm")
                        .HasColumnType("double precision");

                    b.Property<double>("Height_koloshnik")
                        .HasColumnType("double precision");

                    b.Property<double>("Height_raspar")
                        .HasColumnType("double precision");

                    b.Property<double>("Height_shahta")
                        .HasColumnType("double precision");

                    b.Property<double>("Height_zaplechik")
                        .HasColumnType("double precision");

                    b.Property<double>("Kolvo_furm")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<double>("Uroven_zasypi")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("FurnaceGeometryInputs");
                });

            modelBuilder.Entity("Core.Models.GasDynamic.Base.Inputs.MaterialProperties", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<double>("Massa_aglo")
                        .HasColumnType("double precision");

                    b.Property<double>("Massa_koks_kg")
                        .HasColumnType("double precision");

                    b.Property<double>("Massa_okat")
                        .HasColumnType("double precision");

                    b.Property<double>("Plotn_shlak")
                        .HasColumnType("double precision");

                    b.Property<double>("Porozn_aglo")
                        .HasColumnType("double precision");

                    b.Property<double>("Porozn_okat")
                        .HasColumnType("double precision");

                    b.Property<double>("Poteri_prokalivanie")
                        .HasColumnType("double precision");

                    b.Property<double>("Udeln_vyhod_shlak")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("MaterialProperties");
                });

            modelBuilder.Entity("Core.Models.GasDynamic.Base.Inputs.ProductionParameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Dolya_okat")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<double>("Proizvodit_chugun")
                        .HasColumnType("double precision");

                    b.Property<double>("Stepen_urav_krit")
                        .HasColumnType("double precision");

                    b.Property<double>("Udeln_izvest")
                        .HasColumnType("double precision");

                    b.Property<double>("Udeln_zhelezorud")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("ProductionParameters");
                });

            modelBuilder.Entity("Core.Models.GasDynamic.Base.Inputs.ThermalAndPressureParameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<double>("Davlen_izb_dut")
                        .HasColumnType("double precision");

                    b.Property<double>("Davlen_izb_koloshnik_gaz")
                        .HasColumnType("double precision");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<double>("Perepad_niz")
                        .HasColumnType("double precision");

                    b.Property<double>("Perepad_verh")
                        .HasColumnType("double precision");

                    b.Property<double>("Temp_dut")
                        .HasColumnType("double precision");

                    b.Property<double>("Temp_koks")
                        .HasColumnType("double precision");

                    b.Property<double>("Temp_koloshnik_gaz")
                        .HasColumnType("double precision");

                    b.Property<double>("Teploemk_koks")
                        .HasColumnType("double precision");

                    b.Property<double>("Teplota_nepoln_koks")
                        .HasColumnType("double precision");

                    b.Property<double>("Teplota_nepoln_prir_gaz")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("ThermalAndPressureParameters");
                });

            modelBuilder.Entity("Core.Models.GasDynamic.Base.Outputs.BlastFurnanceOutputModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BlastParametersId")
                        .HasColumnType("integer");

                    b.Property<int>("CarbonBalanceId")
                        .HasColumnType("integer");

                    b.Property<int>("ChargeAndPackingId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FurnaceGeometryId")
                        .HasColumnType("integer");

                    b.Property<int>("HearthGasId")
                        .HasColumnType("integer");

                    b.Property<int>("HydrodynamicsLowerId")
                        .HasColumnType("integer");

                    b.Property<int>("HydrodynamicsUpperId")
                        .HasColumnType("integer");

                    b.Property<int>("IntermediateGas1000Id")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<int>("MaterialConsumptionId")
                        .HasColumnType("integer");

                    b.Property<int>("ThermalParametersId")
                        .HasColumnType("integer");

                    b.Property<int>("TopGasId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BlastParametersId");

                    b.HasIndex("CarbonBalanceId");

                    b.HasIndex("ChargeAndPackingId");

                    b.HasIndex("FurnaceGeometryId");

                    b.HasIndex("HearthGasId");

                    b.HasIndex("HydrodynamicsLowerId");

                    b.HasIndex("HydrodynamicsUpperId");

                    b.HasIndex("IntermediateGas1000Id");

                    b.HasIndex("MaterialConsumptionId");

                    b.HasIndex("ThermalParametersId");

                    b.HasIndex("TopGasId");

                    b.ToTable("BlastFurnanceOutputs");
                });

            modelBuilder.Entity("Core.Models.GasDynamic.Base.Outputs.BlastParameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<double>("Rashod_Dut_Koks")
                        .HasColumnType("double precision");

                    b.Property<double>("Rashod_Dut_Krit")
                        .HasColumnType("double precision");

                    b.Property<double>("Rashod_Dut_Minut")
                        .HasColumnType("double precision");

                    b.Property<double>("Rashod_Dut_Prir_Gaz")
                        .HasColumnType("double precision");

                    b.Property<double>("Rashod_Dut_Sum")
                        .HasColumnType("double precision");

                    b.Property<double>("Rashod_Dut_Udeln")
                        .HasColumnType("double precision");

                    b.Property<double>("Reinolds")
                        .HasColumnType("double precision");

                    b.Property<double>("Speed_Dut_Furm")
                        .HasColumnType("double precision");

                    b.Property<double>("Vyazkost_Dut")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("BlastParameters");
                });

            modelBuilder.Entity("Core.Models.GasDynamic.Base.Outputs.CarbonBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("C_Input")
                        .HasColumnType("double precision");

                    b.Property<double>("C_Out_Chugun")
                        .HasColumnType("double precision");

                    b.Property<double>("C_Out_Furm")
                        .HasColumnType("double precision");

                    b.Property<double>("C_Out_Metan")
                        .HasColumnType("double precision");

                    b.Property<double>("C_Out_Vosstan")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CarbonBalances");
                });

            modelBuilder.Entity("Core.Models.GasDynamic.Base.Outputs.ChargeAndPacking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Diam_Aglo")
                        .HasColumnType("double precision");

                    b.Property<double>("Diam_Koks")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<double>("Massa_Nasyp_Shihta")
                        .HasColumnType("double precision");

                    b.Property<double>("Porozn_Aglo")
                        .HasColumnType("double precision");

                    b.Property<double>("Porozn_Koks")
                        .HasColumnType("double precision");

                    b.Property<double>("Porozn_Okat")
                        .HasColumnType("double precision");

                    b.Property<double>("Porozn_Sloy_Korrekt")
                        .HasColumnType("double precision");

                    b.Property<double>("Shihta_Diam_Verh")
                        .HasColumnType("double precision");

                    b.Property<double>("Shihta_Dolya_Aglo")
                        .HasColumnType("double precision");

                    b.Property<double>("Shihta_Dolya_Koks")
                        .HasColumnType("double precision");

                    b.Property<double>("Shihta_Dolya_Okat")
                        .HasColumnType("double precision");

                    b.Property<double>("Shihta_Porozn_Verh")
                        .HasColumnType("double precision");

                    b.Property<double>("Volume_Aglo_1chugun")
                        .HasColumnType("double precision");

                    b.Property<double>("Volume_Koks_1chugun")
                        .HasColumnType("double precision");

                    b.Property<double>("Volume_Okat_1chugun")
                        .HasColumnType("double precision");

                    b.Property<double>("Volume_Sum_1chugun")
                        .HasColumnType("double precision");

                    b.Property<double>("Volume_Udeln_Koks")
                        .HasColumnType("double precision");

                    b.Property<double>("Volume_Udeln_Nasadzka")
                        .HasColumnType("double precision");

                    b.Property<double>("Volume_Udeln_Ost")
                        .HasColumnType("double precision");

                    b.Property<double>("Volume_Udeln_Shlak")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("ChargeAndPackings");
                });

            modelBuilder.Entity("Core.Models.GasDynamic.Base.Outputs.FurnaceGeometry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Diam_Niz")
                        .HasColumnType("double precision");

                    b.Property<double>("Diam_Verh")
                        .HasColumnType("double precision");

                    b.Property<double>("Height_Aktiv")
                        .HasColumnType("double precision");

                    b.Property<double>("Height_Shihta_Niz")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<double>("S_Sech_Niz")
                        .HasColumnType("double precision");

                    b.Property<double>("Shihta_Height_Verh")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("FurnaceGeometryOutputs");
                });

            modelBuilder.Entity("Core.Models.GasDynamic.Base.Outputs.HearthGas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Furmgaz_CO")
                        .HasColumnType("double precision");

                    b.Property<double>("Furmgaz_CO_V")
                        .HasColumnType("double precision");

                    b.Property<double>("Furmgaz_H2")
                        .HasColumnType("double precision");

                    b.Property<double>("Furmgaz_H2_V")
                        .HasColumnType("double precision");

                    b.Property<double>("Furmgaz_Koks")
                        .HasColumnType("double precision");

                    b.Property<double>("Furmgaz_N2")
                        .HasColumnType("double precision");

                    b.Property<double>("Furmgaz_N2_V")
                        .HasColumnType("double precision");

                    b.Property<double>("Furmgaz_Prir_Gaz")
                        .HasColumnType("double precision");

                    b.Property<double>("Furmgaz_Sum")
                        .HasColumnType("double precision");

                    b.Property<double>("Furmgaz_Udeln")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<double>("Temp_Sredn_Niz")
                        .HasColumnType("double precision");

                    b.Property<double>("Temp_Teor")
                        .HasColumnType("double precision");

                    b.Property<double>("Teplosod_Furmgaz")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("HearthGases");
                });

            modelBuilder.Entity("Core.Models.GasDynamic.Base.Outputs.HydrodynamicsLower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<double>("Davlen_Izb_1000")
                        .HasColumnType("double precision");

                    b.Property<double>("Davlen_Niz")
                        .HasColumnType("double precision");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Koef_An")
                        .HasColumnType("double precision");

                    b.Property<double>("Koef_Proporc_Dut_Filtr_Niz")
                        .HasColumnType("double precision");

                    b.Property<double>("Koef_Soprot_Niz")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<double>("Perepad_Niz_Dolya")
                        .HasColumnType("double precision");

                    b.Property<double>("Perepad_Niz_Itog")
                        .HasColumnType("double precision");

                    b.Property<double>("Poteri_Furm")
                        .HasColumnType("double precision");

                    b.Property<double>("Speed_Filtr_Niz")
                        .HasColumnType("double precision");

                    b.Property<double>("Tren_Koef")
                        .HasColumnType("double precision");

                    b.Property<double>("Tren_Sum")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("HydrodynamicsLowers");
                });

            modelBuilder.Entity("Core.Models.GasDynamic.Base.Outputs.HydrodynamicsUpper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<double>("Davlen_Verh")
                        .HasColumnType("double precision");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Koef_Av")
                        .HasColumnType("double precision");

                    b.Property<double>("Koef_Proporc_Dut_Filtr_Verh")
                        .HasColumnType("double precision");

                    b.Property<double>("Koef_Soprot_Verh")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<double>("Perepad_Davlen")
                        .HasColumnType("double precision");

                    b.Property<double>("Speed_Filtr_Gorn")
                        .HasColumnType("double precision");

                    b.Property<double>("Speed_Filtr_Koloshnik")
                        .HasColumnType("double precision");

                    b.Property<double>("Speed_Filtr_Raspar")
                        .HasColumnType("double precision");

                    b.Property<double>("Speed_Filtr_Verh")
                        .HasColumnType("double precision");

                    b.Property<double>("Speed_Real_Koloshnik")
                        .HasColumnType("double precision");

                    b.Property<double>("Speed_Real_Raspar")
                        .HasColumnType("double precision");

                    b.Property<double>("Speed_Real_Verh")
                        .HasColumnType("double precision");

                    b.Property<double>("Stepen_Urav")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("HydrodynamicsUppers");
                });

            modelBuilder.Entity("Core.Models.GasDynamic.Base.Outputs.IntermediateGas1000", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Domengaz_CO_1000")
                        .HasColumnType("double precision");

                    b.Property<double>("Domengaz_H2_1000")
                        .HasColumnType("double precision");

                    b.Property<double>("Domengaz_N2_1000")
                        .HasColumnType("double precision");

                    b.Property<double>("Domengaz_Plotn_1000")
                        .HasColumnType("double precision");

                    b.Property<double>("Domengaz_Rashod_1000")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<double>("Volume_CO_1000")
                        .HasColumnType("double precision");

                    b.Property<double>("Volume_CO_Pvost")
                        .HasColumnType("double precision");

                    b.Property<double>("Volume_H2_1000")
                        .HasColumnType("double precision");

                    b.Property<double>("Volume_N2_1000")
                        .HasColumnType("double precision");

                    b.Property<double>("Volume_Sum_1000")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("IntermediateGases1000");
                });

            modelBuilder.Entity("Core.Models.GasDynamic.Base.Outputs.MaterialConsumption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<double>("Rashod_Prir_Gaz")
                        .HasColumnType("double precision");

                    b.Property<double>("Udeln_Aglo")
                        .HasColumnType("double precision");

                    b.Property<double>("Udeln_Izvest")
                        .HasColumnType("double precision");

                    b.Property<double>("Udeln_Koks_1000")
                        .HasColumnType("double precision");

                    b.Property<double>("Udeln_Okat")
                        .HasColumnType("double precision");

                    b.Property<double>("Udeln_Sum")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("MaterialConsumptions");
                });

            modelBuilder.Entity("Core.Models.GasDynamic.Base.Outputs.ThermalParameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<double>("Temp_Verh")
                        .HasColumnType("double precision");

                    b.Property<double>("Teploemk_2atom")
                        .HasColumnType("double precision");

                    b.Property<double>("Teploemk_Voda")
                        .HasColumnType("double precision");

                    b.Property<double>("Teplosod_Dut")
                        .HasColumnType("double precision");

                    b.Property<double>("Teplosod_Koks")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("ThermalParameters");
                });

            modelBuilder.Entity("Core.Models.GasDynamic.Base.Outputs.TopGas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Kolgaz_CH4")
                        .HasColumnType("double precision");

                    b.Property<double>("Kolgaz_CO")
                        .HasColumnType("double precision");

                    b.Property<double>("Kolgaz_CO2")
                        .HasColumnType("double precision");

                    b.Property<double>("Kolgaz_H2")
                        .HasColumnType("double precision");

                    b.Property<double>("Kolgaz_Minut")
                        .HasColumnType("double precision");

                    b.Property<double>("Kolgaz_N2")
                        .HasColumnType("double precision");

                    b.Property<double>("Kolgaz_Plotn")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<double>("Udeln_Kolgaz")
                        .HasColumnType("double precision");

                    b.Property<double>("Volume_CH4_Kolgaz")
                        .HasColumnType("double precision");

                    b.Property<double>("Volume_CO2_Izvest")
                        .HasColumnType("double precision");

                    b.Property<double>("Volume_CO2_Kolgaz")
                        .HasColumnType("double precision");

                    b.Property<double>("Volume_CO2_Kvost")
                        .HasColumnType("double precision");

                    b.Property<double>("Volume_CO_Kolgaz")
                        .HasColumnType("double precision");

                    b.Property<double>("Volume_H2_Kolgaz")
                        .HasColumnType("double precision");

                    b.Property<double>("Volume_N2_Kolgaz")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("TopGases");
                });

            modelBuilder.Entity("Core.Models.GasDynamic.RequestModelV2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AglomInputId")
                        .HasColumnType("integer");

                    b.Property<int>("BlastFurnaceInputId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPreset")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AglomInputId");

                    b.HasIndex("BlastFurnaceInputId");

                    b.ToTable("CalculationInputs");
                });

            modelBuilder.Entity("Core.Models.GasDynamic.ResponseModelV2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AglomOutputId")
                        .HasColumnType("integer");

                    b.Property<int>("BlastFurnanceOutputId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorID")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedByID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastEditedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastEditorID")
                        .HasColumnType("integer");

                    b.Property<int>("RequestModelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AglomOutputId");

                    b.HasIndex("BlastFurnanceOutputId");

                    b.HasIndex("RequestModelId");

                    b.ToTable("CalculationOutputs");
                });

            modelBuilder.Entity("Core.Models.GasDynamic.Aglom.Inputs.AglomContent", b =>
                {
                    b.HasOne("Core.Models.GasDynamic.Aglom.Inputs.AglomInputModel", "AglomInputModel")
                        .WithMany("AglomContents")
                        .HasForeignKey("AglomInputModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AglomInputModel");
                });

            modelBuilder.Entity("Core.Models.GasDynamic.Aglom.Inputs.KoksContent", b =>
                {
                    b.HasOne("Core.Models.GasDynamic.Aglom.Inputs.AglomInputModel", "AglomInputModel")
                        .WithMany("KoksContents")
                        .HasForeignKey("AglomInputModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AglomInputModel");
                });

            modelBuilder.Entity("Core.Models.GasDynamic.Aglom.Inputs.OkatContent", b =>
                {
                    b.HasOne("Core.Models.GasDynamic.Aglom.Inputs.AglomInputModel", "AglomInputModel")
                        .WithMany("OkatContents")
                        .HasForeignKey("AglomInputModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AglomInputModel");
                });

            modelBuilder.Entity("Core.Models.GasDynamic.Base.Inputs.BlastFurnaceInputModel", b =>
                {
                    b.HasOne("Core.Models.GasDynamic.Base.Inputs.CompositionParameters", "Composition")
                        .WithMany()
                        .HasForeignKey("CompositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.GasDynamic.Base.Inputs.FuelAndBlastParameters", "FuelAndBlast")
                        .WithMany()
                        .HasForeignKey("FuelAndBlastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.GasDynamic.Base.Inputs.FurnaceGeometry", "Geometry")
                        .WithMany()
                        .HasForeignKey("GeometryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.GasDynamic.Base.Inputs.MaterialProperties", "Materials")
                        .WithMany()
                        .HasForeignKey("MaterialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.GasDynamic.Base.Inputs.ProductionParameters", "Production")
                        .WithMany()
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.GasDynamic.Base.Inputs.ThermalAndPressureParameters", "ThermalAndPressure")
                        .WithMany()
                        .HasForeignKey("ThermalAndPressureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Composition");

                    b.Navigation("FuelAndBlast");

                    b.Navigation("Geometry");

                    b.Navigation("Materials");

                    b.Navigation("Production");

                    b.Navigation("ThermalAndPressure");
                });

            modelBuilder.Entity("Core.Models.GasDynamic.Base.Outputs.BlastFurnanceOutputModel", b =>
                {
                    b.HasOne("Core.Models.GasDynamic.Base.Outputs.BlastParameters", "BlastParameters")
                        .WithMany()
                        .HasForeignKey("BlastParametersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.GasDynamic.Base.Outputs.CarbonBalance", "CarbonBalance")
                        .WithMany()
                        .HasForeignKey("CarbonBalanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.GasDynamic.Base.Outputs.ChargeAndPacking", "ChargeAndPacking")
                        .WithMany()
                        .HasForeignKey("ChargeAndPackingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.GasDynamic.Base.Outputs.FurnaceGeometry", "FurnaceGeometry")
                        .WithMany()
                        .HasForeignKey("FurnaceGeometryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.GasDynamic.Base.Outputs.HearthGas", "HearthGas")
                        .WithMany()
                        .HasForeignKey("HearthGasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.GasDynamic.Base.Outputs.HydrodynamicsLower", "HydrodynamicsLower")
                        .WithMany()
                        .HasForeignKey("HydrodynamicsLowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.GasDynamic.Base.Outputs.HydrodynamicsUpper", "HydrodynamicsUpper")
                        .WithMany()
                        .HasForeignKey("HydrodynamicsUpperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.GasDynamic.Base.Outputs.IntermediateGas1000", "IntermediateGas1000")
                        .WithMany()
                        .HasForeignKey("IntermediateGas1000Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.GasDynamic.Base.Outputs.MaterialConsumption", "MaterialConsumption")
                        .WithMany()
                        .HasForeignKey("MaterialConsumptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.GasDynamic.Base.Outputs.ThermalParameters", "ThermalParameters")
                        .WithMany()
                        .HasForeignKey("ThermalParametersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.GasDynamic.Base.Outputs.TopGas", "TopGas")
                        .WithMany()
                        .HasForeignKey("TopGasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlastParameters");

                    b.Navigation("CarbonBalance");

                    b.Navigation("ChargeAndPacking");

                    b.Navigation("FurnaceGeometry");

                    b.Navigation("HearthGas");

                    b.Navigation("HydrodynamicsLower");

                    b.Navigation("HydrodynamicsUpper");

                    b.Navigation("IntermediateGas1000");

                    b.Navigation("MaterialConsumption");

                    b.Navigation("ThermalParameters");

                    b.Navigation("TopGas");
                });

            modelBuilder.Entity("Core.Models.GasDynamic.RequestModelV2", b =>
                {
                    b.HasOne("Core.Models.GasDynamic.Aglom.Inputs.AglomInputModel", "AglomInput")
                        .WithMany()
                        .HasForeignKey("AglomInputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.GasDynamic.Base.Inputs.BlastFurnaceInputModel", "BlastFurnaceInput")
                        .WithMany()
                        .HasForeignKey("BlastFurnaceInputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AglomInput");

                    b.Navigation("BlastFurnaceInput");
                });

            modelBuilder.Entity("Core.Models.GasDynamic.ResponseModelV2", b =>
                {
                    b.HasOne("Core.Models.GasDynamic.Aglom.Outputs.AglomOutputModel", "AglomOutput")
                        .WithMany()
                        .HasForeignKey("AglomOutputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.GasDynamic.Base.Outputs.BlastFurnanceOutputModel", "BlastFurnanceOutput")
                        .WithMany()
                        .HasForeignKey("BlastFurnanceOutputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.GasDynamic.RequestModelV2", "RequestModel")
                        .WithMany()
                        .HasForeignKey("RequestModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AglomOutput");

                    b.Navigation("BlastFurnanceOutput");

                    b.Navigation("RequestModel");
                });

            modelBuilder.Entity("Core.Models.GasDynamic.Aglom.Inputs.AglomInputModel", b =>
                {
                    b.Navigation("AglomContents");

                    b.Navigation("KoksContents");

                    b.Navigation("OkatContents");
                });
#pragma warning restore 612, 618
        }
    }
}
